### ISSUE TITLE
Is this extension unmaintained?

### ISSUE THREAD

**Issue by acederberg** [quarto-ext/include-code-files#11]
I would like to contribute a solution, however it looks like no issues have been addressed and only the pull request for a license has been approved. It would probably be better to maintain this than to maintain a fork or build something else.

Is anyone actively maintaining this? If not, might I offer my help? 

@jjallaire I see you're pretty busy, however I would like to directly solicit your attention here. Please let us know if there's any way we can contribute to the effort to add features (e.g. snippets).

**Comment by cderv** [comment]
Please feel free to contribute. Team is limited, and time that goes with it. We have a lot of project in Quarto ecosytem to focus and even if we are watching this repo, we are not that active short term on adding new feature.

We can definitely review PR. So please do contribute if you want to. 

Thank you for your help !

**Comment by acederberg** [comment]
Gotcha! I'm sorry my other comment came off as harsh. I just really think quarto is amazing and want help make it better. I'll see what I can cook up.

**Comment by cderv** [comment]
Thank you !
